version: "3.5"
services:
  postgres:
    hostname: postgres
    image: postgres:11
    environment:
      POSTGRES_USER: default
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: laravel
      PGDATA: /data/postgres
    volumes:
      - ./pgdata:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - backend
    restart: unless-stopped