version: "3.5"
services:
  postgres:
    hostname: postgres
    image: postgres:11
    environment:
      POSTGRES_USER: default
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: laravel
      PGDATA: /data/postgres
    volumes:
      - ./pgdata:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - backend
    restart: unless-stopped
  auto-ml:
    hostname: auto-ml
    build:
      context: ./auto-ml
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./auto-ml/gensim-data:/root/gensim-data
      - ./auto-ml/start.py:/usr/src/app/start.py
      - ./auto-ml/models:/usr/src/app/models
    ports:
      - "8080:8080"
    networks:
      - backend
    command: ["python", "./start.py"]
  jupyter:
    hostname: jupyter
    build:
      context: ./auto-ml
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./auto-ml/notebook:/usr/src/app/notebook
      - ./auto-ml/gensim-data:/root/gensim-data
    ports:
      - "8888:8888"
    networks:
      - backend
    command: ["jupyter", "notebook", "--ip=0.0.0.0", "--port=8888", "--allow-root"]
  api:
    hostname: api
    image: api-image
    volumes:
      - ./api:/var/www/html
    networks:
      - backend
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      APP_NAME: Laravel
      APP_ENV: local
      APP_KEY: base64:8ULh8JpYt1vUfmzSjm17mjRPu8VTA05YUvW3foSVlts=
      APP_DEBUG: "true"
      APP_URL: http://south.insrt.ru
      LOG_CHANNEL: stack
      DB_CONNECTION: pgsql
      DB_HOST: postgres
      DB_PORT: 5432
      DB_DATABASE: laravel
      DB_USERNAME: default
      DB_PASSWORD: secret
      BROADCAST_DRIVER: log
      CACHE_DRIVER: file
      QUEUE_CONNECTION: sync
      SESSION_DRIVER: file
      SESSION_LIFETIME: 120
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./api:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d/
    networks:
      - backend
    depends_on:
      - api
    restart: unless-stopped
networks:
  backend:
    driver: bridge