version: "3.5"
services:
  postgres:
    hostname: postgres
    image: postgres:11
    environment:
      POSTGRES_USER: default
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: laravel
      PGDATA: /data/postgres
    volumes:
      - ./pgdata:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - backend
    restart: unless-stopped
  auto-ml:
    hostname: auto-ml
    build:
      context: ./auto-ml
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./auto-ml/gensim-data:/root/gensim-data
      - ./auto-ml/start.py:/usr/src/app/start.py
      - ./auto-ml/models:/usr/src/app/models
    ports:
      - "8080:8080"
    networks:
      - backend
    command: ["python", "./start.py"]
  backend_shiva:
    container_name: backend_shiva
    hostname: backend_shiva
    image: api-image-shiva
    volumes:
      - ./api:/var/www/html/backend
    networks:
      - backend
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      APP_NAME: Laravel
      APP_ENV: local
      APP_KEY: base64:8ULh8JpYt1vUfmzSjm17mjRPu8VTA05YUvW3foSVlts=
      APP_DEBUG: "false"
      APP_URL: http://south.insrt.ru/api
      LOG_CHANNEL: stack
      DB_CONNECTION: pgsql
      DB_HOST: postgres
      DB_PORT: 5432
      DB_DATABASE: laravel
      DB_USERNAME: default
      DB_PASSWORD: secret
      BROADCAST_DRIVER: log
      CACHE_DRIVER: file
      QUEUE_CONNECTION: sync
      SESSION_DRIVER: file
      SESSION_LIFETIME: 120
  nginx:
    image: frontend-shiva
    ports:
      - "80:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./api:/var/www/html/backend
    networks:
      - backend
    depends_on:
      - backend_shiva
    restart: unless-stopped
networks:
  backend:
    driver: bridge
